feat: 로또 번호 구현
Learning-Is-Vital-In-Development/23-17-pair-programming-game pull request #16
Opened 2023-10-10 14:36 UTC by doxxx93

## ✏️ 구현 내용

[//]: # (- 구현한 내용, 혹은 구현하고자 한 내용에 대해서 간단하게 적어주세요!)

1. 변경점

코드를 작성하다보니, 점차 MVC 패턴이 보이는 것 같아, 패키지를 정리했습니다.

lotto 패키지에는 향후, number, ticket, draw..? 등의 세부 패키지로 두거나

각각의 로직에 맞게 수정을 하면 되겠다 생각이 들었습니다.

2. 남은 단계로는 로또 번호 생성, 당첨 확인, 수익률 계산과 같은 단계들이 남아있다 생각이 들었습니다.

이에 따라서, 로또 번호 생성 기능 구현이 가장 선행 되어야 한다는 생각이 들었고 해당 되는 작업들의 흐름은

    1. 로또 번호 생성 규칙: 로또 번호는 1부터 45까지 중 6개의 랜덤한 숫자로 구성된다.
    2. 랜덤 로또 번호 생성 기능: 1에 따라 로또 번호를 랜덤으로 생성
    3. 수동 로또 번호 입력 기능: 사용자가 원하는 숫자를 입력해서 수동 생성
    4. 자동 로또 번호 생성 기능: 2 + 3

이 떠올랐습니다.

이 순서로 진행을 해보면 될 것 같습니다.

3. 고민했던 내용

기존에 만들었던 Amount를 재활용 할 수 있을까? 하는 고민을 해봤지만, Amount 클래스는 금액을 처리하는 로직을 갖고 있어서 용도와 범위, 로직등이 달라서 분리하는 게 맞겠다는 생각을 했습니다.

## 🤔 논의하고 싶은 내용 / 질문 등

[//]: # (- 학습 내용 기반의 추가적인 논의나 질문 거리에 대해서 작성해주세요)

1. Kotest Spec 스타일 다양하게 써보기 제안

Kotest에 대한 학습이 병행되면 좋겠단 생각이 들어서 간단하게 Kotest의 주요 Spec 스타일을 찾아보니

    1. FunSpec: 가장 기본적인 테스트 스타일로, xUnit과 매우 유사합니다. 테스트 케이스는 test 함수 안에 작성됩니다.
    2. ShouldSpec: BDD 스타일 테스트를 작성하기 위한 스타일로, 테스트 케이스는 should 함수 안에 작성됩니다.
    3. StringSpec: 각 테스트 케이스는 문자열과 람다의 쌍으로 이루어진 테스트를 지원하며, 테스트가 표현에 집중할 수 있게 해줍니다.
    4. FreeSpec: 복잡하게 구조화된 BDD 스타일 테스트를 작성할 수 있게 해줍니다. 테스트 케이스는 - 연산자를 이용해 나열됩니다.
    5. DescribeSpec: Rspec과 같은 스타일로, 테스트 케이스는 describe와 it 함수 안에 작성됩니다.

와 같이 좀 다양한 방식이 있었습니다.

테스트 코드는 다양하게 즐겨볼 수 있게 위의 스타일중 몇개를 정해서 연달아서 같은 스타일로 작성을 하지는 않기 등의 규칙을 제안해봅니다.

물론, 합당한 이유가 있다면 또 연달아 쓰는 거도 상관 없을 거 같습니다.

2023-10-10 23:43 UTC, this-is-spear submitted a review, later dismissed
패키지 구조가 훨씬 깔끔해졌군요 👍👍
저도 `Kotest Spec` 스타일을 다양하게 활용해보고 싶었는데, 이번 기회에 적극 활용해보겠습니다 ☺️

2023-10-10 23:43 UTC, this-is-spear commented on src/test/kotlin/model/lotto/LottoNumberTest.kt
> +            LottoNumber(45).value shouldBe 45
객체 간 비교하는건 어떨까요 ㅎㅎ
`LottoNumber`라는 친구는 값 객체로 사용할텐데, 동등함을 나타낼 수 있으면 이후 작업이 편해질 듯 해요!

```suggestion
            LottoNumber(1) shouldBe LottoNumber(1)
            LottoNumber(45) shouldBe LottoNumber(45)
```

2023-10-11 01:17 UTC, songkg7 requested changes
PR 을 아주 디테일하게 작성해주셨네요. 아주 좋습니다 👍 

저도 테스트 스펙은 가급적 **다양하게 써보시는걸 추천**드리지만 이걸 제한으로는 두지 않으려고 해요. 각자의 학습 상태에 따라서 스스로 선택하시는게 더 효율적이지 않을까요?

2023-10-11 01:17 UTC, songkg7 commented on src/main/kotlin/model/lotto/LottoNumber.kt
> +        require(value in 1..45) { "로또 번호는 1에서 45 사이여야 합니다." }
이 부분은 건창님이 #14 에서 언급해주신 것처럼 메세지를 상수로 관리하는 방법을 고민해보면 좋을 것 같네요~

2023-10-11 01:17 UTC, songkg7 commented on src/test/kotlin/model/lotto/LottoNumberTest.kt
> +        }
여기 테스트가 실패하는데 한 번 체크해주세요~

2023-10-11 01:21 UTC, doxxx93 commented on src/test/kotlin/model/lotto/LottoNumberTest.kt
> +        }
LottoNumber가 data class가 되어야겠군요

2023-10-11 01:37 UTC, songkg7 submitted a review, later dismissed
벌써 한 사이클이 돌았군요...! 원래 계획대로라면 3주가량 걸려야하는 사이클인데, 다들 적극적이셔서 사이클이 엄청난 속도로 돌고 있습니다 ㅋㅋ 👍 

작성한 코드의 물리적인 양은 많지 않지만, Kotlin 을 사용하면서 kotest 와 ktlint 의 느낌에 좀 익숙해져가는 느낌이 드실까요? 진행방식에 슬슬 감이 좀 오실거라 생각하고, 이 스터디 자체가 POC 인만큼 개선해야할 부분이 느껴지신다면 언제든지 제안부탁드립니다. 기록을 위해 Issue 로 남겨주시는 것도 괜찮을 것 같네요~

2023-10-11 01:37 UTC, songkg7 commented on src/main/kotlin/model/lotto/LottoNumber.kt
> +data class LottoNumber(val value: Int) {
```suggestion
data class LottoNumber(private val value: Int) {
```

LottoNumber 를 값타입으로 사용한다면 외부에서는 value 에 접근하지 못하는게 더 좋지 않을까요?

2023-10-11 01:39 UTC, doxxx93 commented on src/main/kotlin/model/lotto/LottoNumber.kt
> +data class LottoNumber(val value: Int) {
좋은 것 같습니다 마저 작업 좀 더 하고 올려보겠습니다

2023-10-11 02:06 UTC, doxxx93 commented
메세지를 상수로 관리하는 방법을 고민해보다가, companion object는 클래스 내부에 존재하는 싱글톤 인스턴스를 선언할 수 있는 객체임을 알게되어서 도입해봤습니다.

테스트 코드에서도 이 메시지를 사용해볼 수 있을까 시도해보니, companion object의 상수를 public으로 설정하면 된다고는 하는데.. 여러분들의 생각은 어떤가요?

public으로 열어두는것도 괜찮을까요?

또한 test코드에서 상수로 에러메시지로 뽑아서 코드 중복은 제거 했지만, 더 나은 방법이 있을 것 같다면 얘기나눠봐요 ㅎ_ㅎ

괜찮은 것 같다면 바톤.. 넘기기하겠습니다

2023-10-11 05:17 UTC, this-is-spear approved these changes
저는 `final` 키워드가 붙은 친구 중에 외부에서 접근을 해야 한다면 `public` 으로 오픈하고 있습니다. 결국 getter 메서드를 만들 필요가 없어지는 거죠 ㅎㅎ  하지만 `companion object`에서는 어떤 단점이 있을지 감이 안오는 군요 ㅜㅜ 이번 기회에 `public` 으로 열어서 같이 경험해보는건 어떨까요? ☺️

`$input` 같은 키워드는 캐싱이 안되더라구요 😭 이 부분은 아쉽지만 `formatter method`로 대체 할 수 있어 보입니다 ㅎㅎ 

도율님 덕분에 코테스트 스펙도 알아갈 수 있었습니다. 감사합니다 😊
수고하셨습니다!

2023-10-11 05:43 UTC, doxxx93 commented
> 저는 `final` 키워드가 붙은 친구 중에 외부에서 접근을 해야 한다면 `public` 으로 오픈하고 있습니다. 결국 getter 메서드를 만들 필요가 없어지는 거죠 ㅎㅎ 하지만 `companion object`에서는 어떤 단점이 있을지 감이 안오는 군요 ㅜㅜ 이번 기회에 `public` 으로 열어서 같이 경험해보는건 어떨까요? ☺️
> 
> `$input` 같은 키워드는 캐싱이 안되더라구요 😭 이 부분은 아쉽지만 `formatter method`로 대체 할 수 있어 보입니다 ㅎㅎ
> 
> 도율님 덕분에 코테스트 스펙도 알아갈 수 있었습니다. 감사합니다 😊 수고하셨습니다!

companion object에서 정적 팩토리 메서드나 변환 관련 함수를 넣었던 거 같은데 두분은 현재 일단 쳐보면서 진행중이신가요? 참고중인 서적이나 강의가 있을까요? 뭐니뭐니해도 레퍼런스 보기..?

2023-10-11 06:22 UTC, songkg7 commented
상수 선언 방식에는 companion object 말고도 top-level scope 에 정의하는 방식도 있지만, 일단은 건창님 말씀처럼 아직 확신이 들지 않으면 남겨두고 불편함을 느껴보는 것도 좋겠죠 😂 

서적같은 경우엔 저는 Kotlin In Action 과 공식 레퍼런스를 참고하고 있습니다. 코틀린은 공식 레퍼런스 퀼리티도 아주 훌륭한 편이니까요.

2023-10-11 06:23 UTC, songkg7 approved these changes

2023-10-11 13:19 UTC, merged