Lotto Ticket 구현
Learning-Is-Vital-In-Development/23-17-pair-programming-game pull request #20
Opened 2023-10-23 05:35 UTC by doxxx93

## ✏️ 구현 내용

[//]: # (- 구현한 내용, 혹은 구현하고자 한 내용에 대해서 간단하게 적어주세요!)

- 로또 티켓을 구현해봤습니다. 현재까지는 구매한 내용에 대한 피드백이 존재 하지 않아서, 일단 어설프게라도 구현해봤습니다.
- 수동, 자동 입력을 처리하게 LottoApp 변경도 있었습니다.
- 현재는 자동 로또 티켓을 생성하는 로직이 LottoApp에 있는데, 테스트가 원활한 구조로 변경하기 위해선 로또 티켓 팩토리 도입을 고려해볼까 합니다..

제 차례인걸 까먹고..

코멘트들을 확인후에 추가적으로 작업해보겠습니다.

## 🤔 논의하고 싶은 내용 / 질문 등

[//]: # (- 학습 내용 기반의 추가적인 논의나 질문 거리에 대해서 작성해주세요)

2023-10-23 07:30 UTC, songkg7 requested changes
구현하느라 고생하셨어요~

코드를 살펴보다보니 전체적으로 도메인에 대한 명확한 정의가 먼저 필요할 것 같다는 생각이 드네요.

- `LottoNumber`: 로또 게임을 구성하는 숫자
- `LottoNumbers`: 로또 게임 하나를 구성하는 중복되지 않는 숫자 집합, 6개이며 5개의 일반 숫자와 1개의 보너스 넘버로 구성된다.
- `LottoTicket`: 로또 티켓 한 장, 로또 티켓은 5개의 로또 게임을 포함하며 한 장에 5000원이다.

이런 도메인 설계를 바탕으로 구현이 진행되어야 할 것 같아요. 이 부분에 대해서 의견있으시면 남겨주세요~

2023-10-23 07:30 UTC, songkg7 commented on src/main/kotlin/controller/LottoApp.kt
> +        ) { outputView.printMessage(it) }
수동으로 구매하려는 개수와 로또 번호를 입력받으면 `전체 구입 가능한 수 - 수동 로또 수` 는 자연스럽게 자동으로 구매해야하는 로또가 됩니다. 그렇다면 해당 처리(`generateAutoLottoTickets`)를 `LottoTicket` 이라는 객체가 하게 하고, 현재 위치에서는 완성된 `LottoTicket` 을 반환받는 것이 어떨까요?

2023-10-23 07:30 UTC, songkg7 commented on src/test/kotlin/model/lotto/LottoNumbersTest.kt
> +                exception.message shouldBe INVALID_LOTTO_NUMBER_DUPLICATE_MESSAGE
👍

2023-10-23 07:30 UTC, songkg7 commented on src/test/kotlin/model/lotto/LottoTicketTest.kt
> +        "주어진 LottoNumbers 와 TicketType 을 가진 LottoTicket 을 반환" {
> 테스트는 구현이 아니라 설계를 검증해야 한다

라는 말이 있습니다. 현재는 내부 메서드의 구현을 검증하려고 시도하고 있는 것으로 보여요. LottoTicket 의 내부 구현이 조금이라도 변하면 이 테스트가 깨질 수 있을 것 같다는 생각이 드네요. 조금 더 비즈니스적으로 테스트를 표현하려면 어떻게 해야할까요?

2023-10-23 07:30 UTC, songkg7 commented on src/main/kotlin/model/lotto/LottoTicket.kt
> +data class LottoTicket(
로또는 한 장에 5게임이 들어갈 수 있습니다. 로또 한 장 = `LottoTicket` 이라고 생각해보면 내부적으로 `LottoNumbers` 를 5개 가지고 있어야할 것 같은데 어떠신가요?

2023-10-23 07:34 UTC, doxxx93 commented on src/main/kotlin/controller/LottoApp.kt
> +        ) { outputView.printMessage(it) }
좋은 것 같습니다.

2023-10-23 07:34 UTC, doxxx93 commented on src/main/kotlin/model/lotto/LottoTicket.kt
> +data class LottoTicket(
오 그런 규칙이 있었군요..?

2023-10-23 07:58 UTC, this-is-spear reviewed
수고하셨습니당! 
저는 앞으로의 수정 사항이 반영되면 리뷰하겠습니다!

2023-10-23 07:58 UTC, this-is-spear commented on src/main/kotlin/model/lotto/LottoTicket.kt
> +data class LottoTicket(
앞으로는 정책과의 싸움이 되겠군요 ㅎㅎ

2023-10-23 08:10 UTC, songkg7 commented
로또는 게임당 천원으로, 한 장을 구매하면 5게임을 할 수 있기에 5000원입니다. 그렇다면 수동으로 구매하겠다고 입력하는 카운트는 로또의 게임 수가 되겠네요. 10000원을 입력하면 2장(총10게임)을 살 수 있고, 다음으로 6을 입력하면 수동 5게임을 가진 로또 티켓 한장, 수동1게임 자동4게임을 가진 로또 티켓 한 장을 반환해야 할 것이고... 이런 상호작용을 어떻게 코틀린으로 우아하게 처리할 지 고민해봐야하겠네요~

2023-10-23 09:00 UTC, doxxx93 commented on src/main/kotlin/controller/LottoApp.kt
> +        ) { outputView.printMessage(it) }
업데이트 했습니다!

2023-10-23 09:00 UTC, doxxx93 commented on src/test/kotlin/model/lotto/LottoTicketTest.kt
> +        "주어진 LottoNumbers 와 TicketType 을 가진 LottoTicket 을 반환" {
업데이트.. 해보긴 했는데 명확한 느낌은 아니군요..

2023-10-23 12:53 UTC, this-is-spear reviewed
코멘트 달기 조금 이르지만 원활한 소통을 위해 빠르게 달았습니다! ㅎㅎ
코드를 보면서 `코틀린 코드가 점점 늘어나도 관리가 용이하겠구나` 라는 생각이 들었습니다!
열심히 `코틀린 인 액션` 책을 읽으면서 따라가도록 하겠습니다!

2023-10-23 12:53 UTC, this-is-spear commented on src/main/kotlin/model/lotto/LottoNumbers.kt
> +    }
이 두개의 메서드는 사용되지 않는듯 해용 ㅜㅜ

2023-10-23 12:53 UTC, this-is-spear commented on src/main/kotlin/model/lotto/LottoTicket.kt
> +object LottoTicketGenerator {
`LottoTicketGenerator` 이름을 봤을 때 로또 티켓을 생성하는 책임을 가진 듯 해요 ㅎㅎ 

하지만 내부 구현은 자동으로 생성되는 친구들만을 생성해주는 듯 한데, `LottoApp` 에 존재하는 수동 생성하는 행위를 이 친구에게 맡기는건 어떨까요?

2023-10-23 12:53 UTC, this-is-spear commented on src/test/kotlin/model/lotto/LottoTicketTest.kt
> +        "LottoTicket 생성기" - {
로또 생성기의 책임은 `로또 티켓을 생성해준다` 처럼 보이는데, 그에 맞게 어떠한 `입력값`을 입력했을 때 `어떤` 로또 티켓을 `얼만큼` 생성해주는지만 테스트하는건 어떨까용?!

저는 깨지지 않는 테스트를 유지하기 위해 메서드의 입력값과 결과값을 활용해 경계를 테스트하고 있습니다. ㅎㅎ

2023-10-24 02:16 UTC, doxxx93 commented on src/main/kotlin/model/lotto/LottoNumbers.kt
> +    }
테스트 코드에서 사용을 하긴 하는데.. 사실 만들면서도 고민이 좀 됐습니다.

어떻게 처리하는 게 좋을까요 ?

2023-10-24 02:16 UTC, doxxx93 commented on src/main/kotlin/model/lotto/LottoTicket.kt
> +object LottoTicketGenerator {
아마 입력받은 값을 넘기는 방향으로 구현을 하면 될 것 같군요?

2023-10-24 02:17 UTC, doxxx93 commented on src/test/kotlin/model/lotto/LottoTicketTest.kt
> +        "LottoTicket 생성기" - {
반영해 봐야겠군요 ㅎ_ㅎ

2023-10-24 08:06 UTC, this-is-spear commented on src/main/kotlin/model/lotto/LottoTicket.kt
> +object LottoTicketGenerator {
말씀하신게 맞는 것 같아요!

2023-10-24 13:52 UTC, songkg7 commented on src/main/kotlin/model/lotto/LottoNumbers.kt
> +    }
테스트 코드에서만 필요한 메서드는 사실 비즈니스 관점에서는 의미가 (아직) 없을 수도 있어요. 이전에 언급했던 바와 같이, `설계가 아닌 구현을 테스트하기 위한 메서드가 아닌가?` 라는 관점에서 생각해보시면 좋을 것 같고, 경우에 따라서 과감하게 제거하는 편이 로직을 더 단순하게 만드는 경우도 있다고 생각합니다~ 🤔

2023-10-24 14:32 UTC, doxxx93 reviewed
리뷰 주셨던 내용들 좀 더 살펴보았습니다.

2023-10-24 14:34 UTC, doxxx93 commented on src/test/kotlin/model/lotto/LottoTicketTest.kt
> +        "LottoTicket 생성기" - {
작성을 해보긴 했는데 코멘트 의도대로 잘 풀었는지는.. 모르겠군요

향후 두분의 구현으로.. 알아보겠습니다.

2023-10-25 01:14 UTC, songkg7 approved these changes

2023-10-25 01:18 UTC, this-is-spear approved these changes
수고하셨습니다!!

2023-10-25 01:18 UTC, this-is-spear commented on src/main/kotlin/model/lotto/LottoNumbers.kt
> +    }
경계 값을 테스트한다면 해당 로직으로 검증하지 않아도 될 듯 해요 ㅎㅎ
6개와 일치해야 한다면 (1) 6개보다 작은 케이스, (2) 6개인 케이스, (3) 6개보다 큰 케이스를 검증해도 될 듯 하고, 중복된 숫자들이 없어야 한다면 (4) 중복된 숫자를 넣는 케이스, (5) 중복된 숫자를 넣지 않은 케이스 총 5 번의 케이스로도 메서드 없이 `LottoNumbers` 를 검증할 수 있어보입니다!

2023-10-25 04:09 UTC, merged